### PR TITLE
Migration to remove DDS tables/columns/constraints

### PR DESCRIPTION
**Pull request by akmiller01**

### CODE REVIEW

**Comment by akmiller01** [comment]
Successfully tested a refreshloop locally with new migration:
```
$ python3 src/handler.py -t refreshloop
2021-08-05 13:29:33,802 - refresh - INFO - DB upgrading to version 0.1.9
2021-08-05 13:29:33,802 - refresh - INFO - Making schema upgrade in migration 9
2021-08-05 13:29:33,813 - refresh - INFO - Start service loop
2021-08-05 13:29:33,813 - refresh - INFO - Begin refresh
2021-08-05 13:29:33,813 - refresh - INFO - Syncing publishers from the Registry...
```

**Comment by akmiller01** [comment]
Currently getting an error... Seeing whether it's a function of my migration or perhaps local dev env configuration:
```
    stale_datasets = db.getFilesNotSeenAfter(conn, start_dt)
  File "/home/alex/git/refresher/src/library/db.py", line 511, in getFilesNotSeenAfter
    cur.execute(sql, data)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by akmiller01** [comment]
Made it through the refresh with that last commit!
```
python3 handler.py -t refresh
2021-08-06 09:02:04,619 - refresh - INFO - DB at correct version
2021-08-06 09:02:04,619 - refresh - INFO - Begin refresh
2021-08-06 09:02:04,619 - refresh - INFO - Syncing publishers from the Registry...
2021-08-06 09:14:39,179 - refresh - INFO - Publishers synced. Updating publishers in DB...
2021-08-06 09:14:39,179 - refresh - INFO - Syncing documents from the Registry...
2021-08-06 09:15:10,252 - refresh - INFO - ...Registry result got. Updating DB...
2021-08-06 09:15:19,129 - refresh - INFO - Documents synced.
2021-08-06 09:15:19,129 - refresh - INFO - End refresh.
```

**Review by alexlydiate — APPROVED** [review]
Good stuff - that looks comprehensive. I was looking at your mig_9 thinking...I've got a mig_10, that aint gonna work...but I see you've promoted it to mig_11 :)

Proof is in the pudding, of course - deploy to Dev!

**Pull request merged**
